on: [push]
jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      name: Checkout

    - uses: actions/setup-node@v2
      name: Setup Node
      with:
        node-version: '14'

    - run: npm ci
      name: Install Dependencies

    - run: npm test
      name: Run Unit Tests

    - run: npm run e2e
      name: Run Cypress Tests

    - run: npm run build
      name: Build Applications

    - uses: actions/upload-artifact@v2
      with:
        name: card-games-app
        path: |
          dist/apps/card-games/**/*.*
